# Generated by Django 5.0.1 on 2024-01-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_rest_api', '0002_delete_openweathermapapi_delete_reservamosapi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='TemperatureReport',
        ),
    ]
